import { defineConfig, devices } from "@playwright/test";

/** Synthetic production-component UI only: no Next server, login, bindings or live data. */
export default defineConfig({
  testDir: "./e2e",
  testMatch: [
    "scoped-recommendations.spec.ts",
    "reading-workspace.spec.ts",
    "recommendation-reasons.spec.ts",
    "immersive-articles.spec.ts",
    "immersive-continuity.spec.ts",
    "immersive-summaries.spec.ts",
    "immersive-autoplay-narration.spec.ts",
    "immersive-native-video.spec.ts",
    "immersive-quality.spec.ts",
    "reader-motion.spec.ts",
    "reader-title.spec.ts",
    "quick-reading-settings.spec.ts",
    "settings-navigation.spec.ts",
    "json-restore.spec.ts",
    "feed-retry-status.spec.ts",
    "read-state-sync-recovery.spec.ts",
    "saved-search-keyboard.spec.ts",
    "feed-view-tabs.spec.ts",
    "nsfw-mode-exit.spec.ts",
    "save-url.spec.ts",
    "article-note.spec.ts",
    "feed-add-paste.spec.ts",
    "article-actions-keyboard.spec.ts",
    "feed-menu-keyboard.spec.ts",
    "mcp-consent-navigation.spec.ts",
    "ogp-queue.spec.ts",
    "thumbnail-candidates.spec.ts",
    "push-test-feedback.spec.ts",
  ],
  timeout: 30_000,
  forbidOnly: !!process.env.CI,
  retries: 0,
  workers: 1,
  reporter: [["list"], ["html", { open: "never" }]],
  use: {
    serviceWorkers: "block",
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],
});
