name = "rss-reader"
main = "src/worker.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "rss.0g0.xyz", custom_domain = true }
]

[vars]
GITHUB_OWNER = "g-kari"
GITHUB_REPO = "rss"
GITHUB_BRANCH = "master"

# シークレットは以下で設定:
# npx wrangler secret put GITHUB_TOKEN
