/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=config/search-index.local.jsonc --include-runtime=false --env-interface=SearchIndexEnv src/search-index-env.d.ts` (hash: 9053e04ec093cb31b3ab696256d161fa)
interface __BaseEnv_SearchIndexEnv {
  RSS_DATA: R2Bucket;
  ARTICLE_SEARCH: D1Database;
}
declare namespace Cloudflare {
  interface Env extends __BaseEnv_SearchIndexEnv {}
}
interface SearchIndexEnv extends __BaseEnv_SearchIndexEnv {}
