import type { useKeyboardNav } from "../../src/hooks/useKeyboardNav";

const noop = () => {};

/** Real global keyboard hook options with safe, inert actions and one selected article. */
export function makeKeyboardNavFixture(): Parameters<typeof useKeyboardNav>[0] {
  return {
    filteredArticles: [],
    feeds: [],
    pinnedFeedIds: new Set(),
    selectedFeedId: null,
    selectedArticle: {
      id: "synthetic-selected",
      feedHash: "synthetic",
      guid: "synthetic-selected",
      title: "Synthetic article",
      link: "https://example.test/article",
      summary: "Synthetic excerpt",
      publishedAt: null,
      createdAt: "2026-10-04T00:00:00Z",
    },
    readIds: new Set(),
    readBeforeTimestamp: null,
    readingListIds: new Set(),
    likeIds: new Set(),
    setSelectedArticle: noop,
    onSelectFeed: noop,
    markRead: noop,
    markBulkRead: noop,
    markAllRead: noop,
    toggleBookmark: noop,
    toggleRead: noop,
    toggleReadingList: noop,
    toggleLike: noop,
    showToast: noop,
    fontSize: "medium",
    onChangeFontSize: noop,
    fontFamily: "sans",
    onChangeFontFamily: noop,
    layout: "list",
    onChangeLayout: noop,
    unreadOnly: false,
    toggleUnreadOnly: noop,
    bookmarkOnly: false,
    toggleBookmarkOnly: noop,
    readingListOnly: false,
    toggleReadingListOnly: noop,
    likeOnly: false,
    toggleLikeOnly: noop,
    noteOnly: false,
    toggleNoteOnly: noop,
    resetAllFilters: noop,
    digestMode: false,
    toggleDigestMode: noop,
    toggleSortOrder: () => "newest",
    cycleDateRange: () => "all",
    cycleReadingTimeRange: () => "all",
    readingTimeRange: "all",
    searchRef: { current: null },
    refreshFeeds: async () => {},
    retryFeed: async () => {},
    snoozeArticle: noop,
    onShowSnoozeMenu: noop,
    onShowFeedSwitcher: noop,
    onShowReadingStats: noop,
    confirm: async () => false,
    autoMode: false,
    toggleAutoMode: noop,
    ttsSupported: false,
    cycleTtsRate: () => 1,
  };
}
